name: Upload to Viam Registry

on:
  push:
  release:
    types: [published]

env:
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [arm64, amd64]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make module.tar.gz
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: module-${{ matrix.platform }}
          path: |
            module.tar.gz
            meta.json

  upload:
    needs: build
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'release' }}
    strategy:
      matrix:
        platform: [arm64, amd64]
      max-parallel: 1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: module-${{ matrix.platform }}
      - name: upload
        uses: viamrobotics/upload-module@main
        with:
          module-path: module.tar.gz
          platform: linux/${{ matrix.platform }}
          version: ${{ env.VERSION }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}
