name: Upload Release to Viam Registry

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [arm64, amd64]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make module.tar.gz
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: module-${{ matrix.platform }}
          path: module.tar.gz

  upload:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [arm64, amd64]
      max-parallel: 1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: module-${{ matrix.platform }}
      - name: upload
        uses: viamrobotics/upload-module@main
        with:
          module-path: module.tar.gz
          platform: linux/${{ matrix.platform }}
          version: ${{ env.VERSION }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}